# Generated by hand for the changes: add AttentionEvent, add away_start/ended fields
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='away_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='ended_reason',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AttentionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('LOOKING', 'Looking'), ('NOT_LOOKING', 'Not Looking'), ('AWAY_ALERT', 'Away Alert')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('module', models.ForeignKey(on_delete=models.CASCADE, to='courses.module')),
            ],
        ),
    ]